# Generated by Django 5.2.8 on 2026-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="certification",
            name="credential_id",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="credential_url",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="description",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="issue_date",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="issuer",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="title",
        ),
        migrations.AddField(
            model_name="certification",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
