# Generated by Django 5.2.8 on 2026-01-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
