# Generated by Django 5.2.8 on 2026-01-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_recommendation_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="clicked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
