# Generated by Django 5.2.8 on 2026-01-20 04:18

from django.db import migrations


def fix_foreign_key_constraint(apps, schema_editor):
    """
    Fix the foreign key constraint on messages.chat_id to include ON DELETE CASCADE.
    This finds the constraint dynamically and recreates it with CASCADE.
    """
    with schema_editor.connection.cursor() as cursor:
        # Find the foreign key constraint name for chat_id
        cursor.execute("""
            SELECT tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu 
                ON tc.constraint_name = kcu.constraint_name
            WHERE tc.table_name = 'messages'
            AND tc.constraint_type = 'FOREIGN KEY'
            AND kcu.column_name = 'chat_id';
        """)
        result = cursor.fetchone()
        
        if result:
            constraint_name = result[0]
            # Drop the existing constraint
            cursor.execute(f'ALTER TABLE messages DROP CONSTRAINT IF EXISTS "{constraint_name}";')
            # Recreate with CASCADE
            cursor.execute(f"""
                ALTER TABLE messages 
                ADD CONSTRAINT "{constraint_name}" 
                FOREIGN KEY (chat_id) 
                REFERENCES chats(id) 
                ON DELETE CASCADE 
                DEFERRABLE INITIALLY DEFERRED;
            """)


def reverse_fix_foreign_key_constraint(apps, schema_editor):
    """
    Reverse migration: Remove CASCADE (though this is not recommended)
    """
    with schema_editor.connection.cursor() as cursor:
        # Find the foreign key constraint name for chat_id
        cursor.execute("""
            SELECT tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu 
                ON tc.constraint_name = kcu.constraint_name
            WHERE tc.table_name = 'messages'
            AND tc.constraint_type = 'FOREIGN KEY'
            AND kcu.column_name = 'chat_id';
        """)
        result = cursor.fetchone()
        
        if result:
            constraint_name = result[0]
            # Drop the constraint
            cursor.execute(f'ALTER TABLE messages DROP CONSTRAINT IF EXISTS "{constraint_name}";')
            # Recreate without CASCADE (for rollback purposes)
            cursor.execute(f"""
                ALTER TABLE messages 
                ADD CONSTRAINT "{constraint_name}" 
                FOREIGN KEY (chat_id) 
                REFERENCES chats(id) 
                DEFERRABLE INITIALLY DEFERRED;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            fix_foreign_key_constraint,
            reverse_fix_foreign_key_constraint,
        ),
    ]
