# Generated by Django 5.2.8 on 2026-01-22 05:15

import django.db.models.deletion
from django.db import migrations, models


def fix_employee_foreignkey(apps, schema_editor):
    """
    Fix the employee ForeignKey by dropping the old constraint and recreating it
    to point to the primary key instead of staff_id.
    """
    with schema_editor.connection.cursor() as cursor:
        # Find and drop the existing foreign key constraint
        cursor.execute("""
            SELECT tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu 
                ON tc.constraint_name = kcu.constraint_name
            WHERE tc.table_name = 'chats'
            AND tc.constraint_type = 'FOREIGN KEY'
            AND kcu.column_name IN ('staff_id', 'employee_id');
        """)
        result = cursor.fetchone()
        
        if result:
            constraint_name = result[0]
            cursor.execute(f'ALTER TABLE chats DROP CONSTRAINT IF EXISTS "{constraint_name}";')
        
        # Check if column exists and get its current name and type
        cursor.execute("""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = 'chats'
            AND column_name IN ('staff_id', 'employee_id');
        """)
        col_info = cursor.fetchone()
        
        if col_info:
            col_name = col_info[0]
            col_type = col_info[1]
            
            # Rename the column if it's still called staff_id
            if col_name == 'staff_id':
                cursor.execute('ALTER TABLE chats RENAME COLUMN staff_id TO employee_id;')
            
            # Convert the column type from VARCHAR to BIGINT if needed
            if col_type in ('character varying', 'varchar', 'text'):
                # Since staff_id was a string and we can't reliably map it to employee.id,
                # we'll create a new bigint column, drop the old one, and rename
                # First check if employee_id_new already exists (in case of re-run)
                cursor.execute("""
                    SELECT column_name
                    FROM information_schema.columns
                    WHERE table_name = 'chats'
                    AND column_name = 'employee_id_new';
                """)
                if not cursor.fetchone():
                    cursor.execute('ALTER TABLE chats ADD COLUMN employee_id_new bigint;')
                cursor.execute('ALTER TABLE chats DROP COLUMN IF EXISTS employee_id;')
                cursor.execute('ALTER TABLE chats RENAME COLUMN employee_id_new TO employee_id;')
        else:
            # Column doesn't exist, create it
            cursor.execute('ALTER TABLE chats ADD COLUMN employee_id bigint;')
        
        # Add the new foreign key constraint pointing to id (primary key)
        cursor.execute("""
            ALTER TABLE chats
            ADD CONSTRAINT chats_employee_id_fk
            FOREIGN KEY (employee_id)
            REFERENCES employees_employee(id)
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED;
        """)


def reverse_fix_employee_foreignkey(apps, schema_editor):
    """
    Reverse migration - restore the old foreign key structure
    """
    with schema_editor.connection.cursor() as cursor:
        # Drop the new constraint
        cursor.execute('ALTER TABLE chats DROP CONSTRAINT IF EXISTS chats_employee_id_fk;')
        
        # Rename column back if needed
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'chats'
            AND column_name = 'employee_id';
        """)
        if cursor.fetchone():
            cursor.execute('ALTER TABLE chats RENAME COLUMN employee_id TO staff_id;')


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_fix_message_cascade"),
        ("employees", "0003_remove_staff_id_department_designation"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    fix_employee_foreignkey,
                    reverse_fix_employee_foreignkey,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="chat",
                    name="employee",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]

