# Generated by Django 5.2.8 on 2026-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_visited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
