# Generated by Django 5.2.8 on 2026-01-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_last_visited_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="staff_id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="designation",
        ),
    ]

