# Generated by Django 5.2.8 on 2026-01-22 05:15

from django.db import migrations, models


def populate_email_from_user(apps, schema_editor):
    """Populate email field from User.email"""
    Employee = apps.get_model('employees', 'Employee')
    User = apps.get_model('auth', 'User')
    
    for employee in Employee.objects.all():
        if employee.user and employee.user.email:
            employee.email = employee.user.email
            employee.save()
        else:
            # If no user or no email, generate a unique email based on employee id
            # or delete the employee if it's orphaned
            if not employee.user:
                # Orphaned employee - delete it or assign a default email
                # For safety, we'll assign a default email
                employee.email = f'employee_{employee.id}@growwise.local'
                employee.save()
            elif employee.user and not employee.user.email:
                # User exists but no email - use username as email or generate one
                if employee.user.username:
                    employee.email = f'{employee.user.username}@growwise.local'
                else:
                    employee.email = f'user_{employee.user.id}@growwise.local'
                employee.save()
    
    # Ensure all emails are unique - handle duplicates
    seen_emails = set()
    for employee in Employee.objects.all().order_by('id'):
        # Handle NULL emails
        if not employee.email:
            employee.email = f'employee_{employee.id}@growwise.local'
            employee.save()
        
        # Handle duplicate emails
        if employee.email in seen_emails:
            # Duplicate email - make it unique
            base_email = employee.email.split('@')[0]
            counter = 1
            new_email = f'{base_email}_{counter}@growwise.local'
            while new_email in seen_emails:
                counter += 1
                new_email = f'{base_email}_{counter}@growwise.local'
            employee.email = new_email
            employee.save()
        seen_emails.add(employee.email)
    
    # Final check - ensure no NULL values remain
    null_count = Employee.objects.filter(email__isnull=True).count()
    if null_count > 0:
        # This shouldn't happen, but handle it just in case
        for employee in Employee.objects.filter(email__isnull=True):
            employee.email = f'employee_{employee.id}@growwise.local'
            employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_remove_staff_id_department_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, null=True, blank=True),
        ),
        migrations.RunPython(populate_email_from_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]

